# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/ksvg': '@latest'
    'frameworks/kauth': '@latest-kf6'
    'frameworks/kcmutils': '@latest-kf6'
    'frameworks/kcodecs': '@latest-kf6'
    'frameworks/kcompletion': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kconfigwidgets': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kjobwidgets': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'frameworks/kpackage': '@latest-kf6'
    'frameworks/kservice': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/solid': '@latest-kf6'
    'frameworks/ksvg': '@latest-kf6'
    'plasma/kwayland': '@same'
    'plasma/libplasma': '@same'
    'plasma/plasma-workspace': '@same'
    'plasma/plasma-activities': '@latest-kf6' # Different versioning due to being a former Framework
    'plasma/plasma-activities-stats': '@latest-kf6' # Different versioning due to being a former Framework
    'plasma/plasma5support': '@same'
